projects:
  app:
    schemPath: src/schema.graphql
    includes: [
      "*.graphql"
      # "schema.graphql", 
      # "prisma.graphql",
    ]
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: src/generated/prisma.graphql
    includes: [
      "*.graphql"
      # "datamodel.graphql",
      # "prisma.graphql",
    ]
    extensions:
      prisma: prisma/prisma.yml
